### ISSUE TITLE
Upgrade to latest version of Holochain

### ISSUE THREAD

**Issue by tibetsprague** [holochain-apps/relay#105]

**Comment by mattyg** [comment]
Refactored the git repo so now `develop` and `develop-0.4` have a working version compatible running on holochain 0.4 rc, while `develop-0.3` has the current release line on holochain 0.3.

When to publish new releases under that branch is still an open question based on how Volla want to prioritize data migration during breaking updates versus just getting on the latest version without data migrationl.
