### ISSUE TITLE
Connection to Holochain frozen as admin from diff groups

### ISSUE THREAD

**Issue by HardDriven** [holochain-apps/relay#170]
Build up some groups yesterday, everything working fine. 6 hours later the app is frozen on both mobile phones. Restarting app, mobile, clearing cache, reinstalling app, no results.

**Comment by HardDriven** [comment]
Other members have the same issue. No way to get back on the app

**Comment by mattyg** [comment]
Hi @HardDriven thanks for the bug report -- can you clarify the app behavior?

Were the apps open and running for 6 hours consistently? Or were they used sporadically and the issue only arose after 6 hours?

What does the "frozen" app look like? What page is it stuck on?

**Comment by Tattitar** [comment]
I had that issue before, I had the latest version of the app and it was frozen, but my OS wasn't updated to the latest version, so I updated and reinstalled the app and everything worked well. 
It was on Volla phone.

**Comment by mattyg** [comment]
This should be resolved in the latest release 0.7.0-beta -- will close this issue for now but please reopen if you experience it again.

**Comment by HardDriven** [comment]
Thanks Matty, I'll dump it in the groups

**Comment by HardDriven** [comment]
Hey Matty, 
![Screenshot_2024-10-23-21-34-59-349_com volla messages](https://github.com/user-attachments/assets/01bc33b0-6afb-4bf5-87b4-9fffeca9bb6c)
after a reinstall, cache cleaning there is a new error popping up

**Comment by mattyg** [comment]
@HardDriven to clarify:

Did you uninstall the previous version or simply install the new version?

Did you clear the app data as well or just the app cache?

**Comment by HardDriven** [comment]
First I updated the app as it was asked by installing, got the error. Deleted the cache, app data and the app and installed the new one. Same error message. Please check your Discord message

**Comment by mattyg** [comment]
Thanks @HardDriven - what android os version are you running?

**Comment by HardDriven** [comment]
Redmi Note 8 Pro
Miui Global 12.0.5 stable 
Android 10 QP1A

**Comment by HardDriven** [comment]
OPPO Reno3 Pro
Android 12
ColorOS vs 12.1

![IMG_20241023_222511_791](https://github.com/user-attachments/assets/dd451bd0-376a-4250-a056-890710a9e40c)

**Comment by HardDriven** [comment]
Samsung S22 Ultra
Android 14
Issue: App frozen

Samsung galaxy S24 ultra 
Android 14  
App frozen

Redmi Note 10 Pro
Miui Global 14.0.2
Android 13 TKQ1
Issue: App frozen

Xiaomi 13T Pro 
HyperOS 1.0.6
Android 14 UP1A
App Frozen

Redmi 10C
MIUI Global 14.0.3 
Android 13 TKQ1
Issue: app frozen
