### ISSUE TITLE
Optionally, restrict editing group title & image to only progenitor agent

### ISSUE THREAD

**Issue by Danfro** [holochain-apps/relay#176]
Currently (v0.7.0 beta) users can change the group title and group icon image. This should only be allowed for group admins I think.

**Comment by mattyg** [comment]
Thanks for the feature request -- I agree it could be a nice feature, maybe set optionally when creating a group. It is the default behavior on some messaging apps to allow any group members to change the group-level settings (facebook messenger, whatsapp, signal).

**Comment by Danfro** [comment]
Out of the three you mentioned, I only know and use Signal. You are right, there I can edit group title. But in Telegram that is not possible. And to be honest, as admin in some groups, I personally consider this an design flaw and issue if every user is permitted to change a groups title and image - in the worst case to something violating group rules. But fair enough, this is not the thing with the highest priority. Its definitely up to you do decide how to proceed here. I just wanted to mention it.

**Comment by mattyg** [comment]
Superseded by #202
