### ISSUE TITLE
Suggestion: use QRC for invitation

### ISSUE THREAD

**Issue by LeoIsBack** [holochain-apps/relay#234]
The invitation code is quite long, which is no issue when the invitation is send electronically, but otherwise very difficult to type-in. I think it would be beneficial if the code could be shared and imported as a QR Code.

**Comment by mattyg** [comment]
Thanks @LeoIsBack - I agree it would be good to have QR codes for the invitation code, as well as deep-linking urls that open the app with an invitation code.

There are two issues to track this ( #152 #10 ) so I'm going to close this ticket as duplicate.

**Comment by LeoIsBack** [comment]
Ok, sorry that I overlooked them!
