### ISSUE TITLE
Submit button disabled when firstName is > 3 characters

### ISSUE THREAD

**Issue by mattyg** [holochain-apps/relay#300]
Steps to reproduce:
- On develop-0.3
- Visit initial account setup page
- Button is enabled
- Type 3 characters in firstname field
- button is disabled

This was accidentally introduced in #295 -- see:
- https://github.com/holochain-apps/volla-messages/pull/295#discussion_r1881023214
- https://github.com/holochain-apps/volla-messages/pull/295#discussion_r1881024050

**Comment by MasterK0927** [comment]
completed in #304
