### ISSUE TITLE
Cant scroll members list when its too long

### ISSUE THREAD

**Issue by tibetsprague** [holochain-apps/relay#88]

**Comment by Danfro** [comment]
What is "long"? With  0.7.0-beta-rc.3 I can scroll the list, altough 2 members is maybe not "long". But might have been fixed already.

**Comment by tibetsprague** [comment]
This was fixedOn Oct 22, 2024, at 8:16 AM, Daniel Frost ***@***.***> wrote:﻿
What is "long"? With  0.7.0-beta-rc.3 I can scroll the list, altough 2 members is maybe not "long". But might have been fixed already.
